#!/usr/bin/env bash

set -e

# Exporting the specific shell we want to work with:

SHELL='/bin/bash'
export SHELL

# install oh my zh
echo "installing Oh My Zh"
/bin/bash -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# install homebrew
echo "installing HomeBrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Standard dotbot pre-configuration:

readonly DOTBOT_DIR='dotbot'
readonly DOTBOT_BIN='bin/dotbot'
readonly BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

readonly ARGS="$@"

cd "$BASEDIR"

# Linking dotfiles:

run_dotbot () {
  local config
  config="$1"

  "$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" \
    -d "$BASEDIR" \
    --plugin-dir dotbot-brewfile \
    --plugin-dir dotbot-pip \
    -c "$config" $ARGS
}

run_dotbot 'steps/terminal.yml' || true
run_dotbot 'steps/dependencies.yml' || true
 setup macos
sh ./macos_settings.sh
